services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  api:
    build: .
    container_name: python_api
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6380

volumes:
  redis_data:

